export enum ACTION_CONST {
  CHANGE_CITY = 'CHANGE_CITY',
  SET_OFFER_LIST = 'SET_OFFER_LIST',
  SET_CURRENT_OFFER = 'SET_CURRENT_OFFER',
  SET_OFFER_LIST_NEAR = 'SET_OFFER_LIST_NEAR',
  SET_AUTHORIZATION_STATUS = 'SET_AUTHORIZATION_STATUS',
  SET_AUTHORIZATION_DATA = 'SET_AUTHORIZATION_DATA',
  SET_FAVORITES = 'SET_FAVORITES',
  SET_COMMENTS = 'SET_COMMENTS',
  LOG_OFF = 'LOG_OFF',
  SET_SORT = 'SET_SORT',
  SET_ACTIVE_OFFER = 'SET_ACTIVE_OFFER'
}
