export const ACTION_CONST = {
  CHANGE_CITY: 'CHANGE_CITY',
  SET_OFFER_LIST: 'SET_OFFER_LIST',
  SET_LOADING: 'SET_LOADING',
  SET_CURRENT_OFFER: 'SET_CURRENT_OFFER',
  SET_OFFER_LIST_NEAR: 'SET_OFFER_LIST_NEAR',
  SET_AUTHORIZATION_STATUS: 'SET_AUTHORIZATION_STATUS',
  SET_AUTHORIZATION_DATA: 'SET_AUTHORIZATION_DATA',
  SET_FAVORITES: 'SET_FAVORITES'
};
